In [3]:
import torch

# tensors
tensor = torch.tensor([[1, 2], [3, 4]])
print("Tensor:")
print(tensor)

print("First row of the tensor:")
print(tensor[0][1])


Tensor:
tensor([[1, 2],
        [3, 4]])
First row of the tensor:
tensor(2)


In [4]:
#operations
tensor_add = tensor +tensor
tensor_mul = tensor * tensor
tensor_matmul = torch.matmul(tensor, tensor)
print("Tensor Addition:")
print(tensor_add)
print("Tensor Multiplication:")
print(tensor_mul)
print("Tensor Matrix Multiplication:")
print(tensor_matmul)

Tensor Addition:
tensor([[2, 4],
        [6, 8]])
Tensor Multiplication:
tensor([[ 1,  4],
        [ 9, 16]])
Tensor Matrix Multiplication:
tensor([[ 7, 10],
        [15, 22]])


In [12]:
#automatic differentiation
x = torch.tensor(2.0, requires_grad=True)
y = x**2

#compute backward
y.backward()
print("Gradient of y with respect to x:", x.grad)

Gradient of y with respect to x: tensor(4.)


In [14]:
from torch.utils.data import Dataset, DataLoader
import pandas as pd


# Generating a simple example dataset dataframe
data = {
    "feature1": [0.5, 1.5, 2.5, 3.5, 4.5, 6.0],
    "feature2": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
    "feature3": [1.5, 2.5, 3.5, 4.5, 5.5, 7.0],
    "target": [2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
}

df = pd.DataFrame(data)

# Dataset
class CustomDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe
        self.features = dataframe.drop("target", axis=1).values
        self.targets = dataframe["target"].values

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        features = torch.tensor(self.features[idx], dtype=torch.float32)
        target = torch.tensor(self.targets[idx], dtype=torch.float32)
        return features, target

# Create an instance of the dataset
dataset = CustomDataset(df)
print(f"The dataset has {len(dataset)} samples")


# Dataloader
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Checking one batch of the dataloader
dataiter = iter(dataloader)
sample_X, sample_y = next(dataiter)
print(f"\n\nSample batch: \n\nX: {sample_X} \n\nY: {sample_y}")

The dataset has 6 samples


Sample batch: 

X: tensor([[4.5000, 5.0000, 5.5000],
        [0.5000, 1.0000, 1.5000]]) 

Y: tensor([6., 2.])


In [15]:
import torch.nn as nn

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        # Declaring the layers to use
        self.fc1 = nn.Linear(3, 2)        # input layer (3 inputs, 2 hidden neurons)
        self.fc2 = nn.Linear(2, 1)        # output layer (2 hidden neurons, 1 output target)
        self.relu = nn.ReLU()            # ReLu activation function

    def forward(self, x):
        # Defining the connections and data flow across layers in the model
        # (2 inputs, 4 hidden neurons + ReLu, 1 output target)
        x = self.fc1(x)               # input to hidden
        x = self.relu(x)             # activation
        x = self.fc2(x)               # hidden to output
        return x                    # output

# Instantiate the network
model = SimpleNN()
print(model)

SimpleNN(
  (fc1): Linear(in_features=3, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
  (relu): ReLU()
)


In [16]:
import torch.optim as optim

# Defining a Loss Function, we use the Mean Squared Error in this case
criterion = nn.MSELoss()

# Defining an Optimizer function, we use Stochastic Gradient Descent
optimizer = optim.SGD(model.parameters(), lr=0.005)       # learning rate of 0.005

In [17]:
# Training loop
for epoch in range(10):
    print(f"---- Epoch {epoch+1} ----")
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()  # Zero the gradients
        outputs = model(X).squeeze()  # Forward pass
        loss = criterion(outputs, y)  # Compute loss
        loss.backward()  # Backward pass
        optimizer.step()  # Update weights

        print(f"Batch {batch+1}, Loss: {loss}")  

---- Epoch 1 ----
Batch 1, Loss: 20.87030029296875
Batch 2, Loss: 5.47598934173584
Batch 3, Loss: 7.932060718536377
---- Epoch 2 ----
Batch 1, Loss: 3.696017265319824
Batch 2, Loss: 0.8965308666229248
Batch 3, Loss: 0.5468356609344482
---- Epoch 3 ----
Batch 1, Loss: 0.16841799020767212
Batch 2, Loss: 0.13174627721309662
Batch 3, Loss: 0.27956822514533997
---- Epoch 4 ----
Batch 1, Loss: 0.21821948885917664
Batch 2, Loss: 0.19246964156627655
Batch 3, Loss: 0.20340344309806824
---- Epoch 5 ----
Batch 1, Loss: 0.16279704868793488
Batch 2, Loss: 0.033678460866212845
Batch 3, Loss: 0.29013609886169434
---- Epoch 6 ----
Batch 1, Loss: 0.10524575412273407
Batch 2, Loss: 0.15835218131542206
Batch 3, Loss: 0.09529048949480057
---- Epoch 7 ----
Batch 1, Loss: 0.05466783419251442
Batch 2, Loss: 0.05647894740104675
Batch 3, Loss: 0.3463205099105835
---- Epoch 8 ----
Batch 1, Loss: 0.1902540922164917
Batch 2, Loss: 0.062352925539016724
Batch 3, Loss: 0.37042754888534546
---- Epoch 9 ----
Batch 1, 

In [22]:
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4060 Laptop GPU'

In [23]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Creating a new sample 
new_X = torch.tensor([2., 3., 3.])

# Move tensor to GPU
new_X = new_X.to(device)
print("New sample:", new_X)

# Move model to GPU
model = model.to(device)

# Inference from GPU
model.eval()
with torch.no_grad():
    pred = model(new_X)
    
print("Prediction:", pred[0])

Using device: cuda
New sample: tensor([2., 3., 3.], device='cuda:0')
Prediction: tensor(3.1472, device='cuda:0')
