In [2]:
import numpy as np
import pandas as pd
import sklearn
import xgboost

df = pd.read_csv("../data/raw/titanic3.csv")
print(df)

      pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00

In [2]:
df.head()


pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [3]:
df.tail()

pclass  survived                       name     sex   age  sibsp  parch  \
1304       3         0       Zabour, Miss. Hileni  female  14.5      1      0   
1305       3         0      Zabour, Miss. Thamine  female   NaN      1      0   
1306       3         0  Zakarian, Mr. Mapriededer    male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin    male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat   body home.dest  
1304    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308  315082   7.8750   NaN        S  NaN    NaN       NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [5]:
df.describe()


pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [6]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [7]:
df.index

RangeIndex(start=0, stop=1309, step=1)

In [8]:
df["age"]

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...   
1304    14.5000
1305        NaN
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [9]:
len(df["age"])

1309

In [10]:
set(df["age"])

{0.1667,
 0.4167,
 0.6667,
 0.75,
 0.9167,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 11.5,
 12.0,
 13.0,
 14.0,
 14.5,
 15.0,
 16.0,
 17.0,
 18.0,
 18.5,
 19.0,
 20.0,
 20.5,
 21.0,
 22.0,
 22.5,
 23.0,
 23.5,
 24.0,
 24.5,
 25.0,
 26.0,
 26.5,
 27.0,
 28.0,
 28.5,
 29.0,
 30.0,
 30.5,
 31.0,
 32.0,
 32.5,
 33.0,
 34.0,
 34.5,
 35.0,
 36.0,
 36.5,
 37.0,
 38.0,
 38.5,
 39.0,
 40.0,
 40.5,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 45.5,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 55.5,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 60.5,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 70.0,
 70.5,
 71.0,
 74.0,
 76.0,
 80.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.3333,
 0.8333,
 nan,

In [11]:
df.iloc[0]

pclass                                   1
survived                                 1
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                    0
parch                                    0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [12]:
df.iloc[0:5, 0:3]

pclass  survived                                             name
0       1         1                    Allen, Miss. Elisabeth Walton
1       1         1                   Allison, Master. Hudson Trevor
2       1         0                     Allison, Miss. Helen Loraine
3       1         0             Allison, Mr. Hudson Joshua Creighton
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)

In [13]:
list(df.ilock[9])

AttributeError: 'DataFrame' object has no attribute 'ilock'

In [14]:
list(df.iloc[9])

[np.int64(1),
 np.int64(0),
 'Artagaveytia, Mr. Ramon',
 'male',
 np.float64(71.0),
 np.int64(0),
 np.int64(0),
 'PC 17609',
 np.float64(49.5042),
 nan,
 'C',
 nan,
 np.float64(22.0),
 'Montevideo, Uruguay']

In [18]:
df.iloc[9]["name"]

'Artagaveytia, Mr. Ramon'

In [19]:
df.iloc[9]

pclass                             1
survived                           0
name         Artagaveytia, Mr. Ramon
sex                             male
age                             71.0
sibsp                              0
parch                              0
ticket                      PC 17609
fare                         49.5042
cabin                            NaN
embarked                           C
boat                             NaN
body                            22.0
home.dest        Montevideo, Uruguay
Name: 9, dtype: object

In [20]:
df.iloc[9]["age"]

np.float64(71.0)

In [21]:
df.head()


pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [29]:
len(df[(df["sex"]=="male") & (df["age"]<10) & (df["survived"]==0)])

18

In [30]:
df[df["name"].str.startswith("Cumings")]

pclass  survived                                               name  \
84       1         0                          Cumings, Mr. John Bradley   
85       1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   

       sex   age  sibsp  parch    ticket     fare cabin embarked boat  body  \
84    male  39.0      1      0  PC 17599  71.2833   C85        C  NaN   NaN   
85  female  38.0      1      0  PC 17599  71.2833   C85        C    4   NaN   

       home.dest  
84  New York, NY  
85  New York, NY

In [33]:
df.groupby("age")["age"].sum()

age
0.1667       0.1667
0.3333       0.3333
0.4167       0.4167
0.6667       0.6667
0.7500       2.2500
             ...   
70.5000     70.5000
71.0000    142.0000
74.0000     74.0000
76.0000     76.0000
80.0000     80.0000
Name: age, Length: 98, dtype: float64

In [34]:
df.sort_values(by="age")

pclass  survived                                     name     sex  \
763        3         1  Dean, Miss. Elizabeth Gladys "Millvina"  female   
747        3         0  Danbom, Master. Gilbert Sigvard Emanuel    male   
1240       3         1          Thomas, Master. Assad Alexander    male   
427        2         1                Hamalainen, Master. Viljo    male   
658        3         1            Baclini, Miss. Helene Barbara  female   
...      ...       ...                                      ...     ...   
1293       3         0        Williams, Mr. Howard Hugh "Harry"    male   
1297       3         0                   Wiseman, Mr. Phillippe    male   
1302       3         0                        Yousif, Mr. Wazli    male   
1303       3         0                    Yousseff, Mr. Gerious    male   
1305       3         0                    Zabour, Miss. Thamine  female   

         age  sibsp  parch      ticket     fare cabin embarked boat  body  \
763   0.1667      1      2   C.A. 2315  20.5750   NaN        S   10   NaN   
747   0.3333      0      2      347080  14.4000   NaN        S  NaN   NaN   
1240  0.4167      0      1        2625   8.5167   NaN        C   16   NaN   
427   0.6667      1      1      250649  14.5000   NaN        S    4   NaN   
658   0.7500      2      1        2666  19.2583   NaN        C    C   NaN   
...      ...    ...    ...         ...      ...   ...      ...  ...   ...   
1293     NaN      0      0    A/5 2466   8.0500   NaN        S  NaN   NaN   
1297     NaN      0      0  A/4. 34244   7.2500   NaN        S  NaN   NaN   
1302     NaN      0      0        2647   7.2250   NaN        C  NaN   NaN   
1303     NaN      0      0        2627  14.4583   NaN        C  NaN   NaN   
1305     NaN      1      0        2665  14.4542   NaN        C  NaN   NaN   

                       home.dest  
763   Devon, England Wichita, KS  
747                  Stanton, IA  
1240                         NaN  
427                  Detroit, MI  
658           Syria New York, NY  
...                          ...  
1293                         NaN  
1297                         NaN  
1302                         NaN  
1303                         NaN  
1305                         NaN  

[1309 rows x 14 columns]

In [37]:
data = np.random.rand(2,3,4)
print(data)
zeroes = np.zeros((2,2,2))
print(f'zeroes are: {zeroes}')
ones = np.ones((2,2,2))
print(f'ones are: {ones}')
full = np.full((2,2,2),7)
print(f'fulls are: {full}')

[[[0.35646343 0.43834858 0.48581088 0.15098541]
  [0.60829044 0.4784295  0.79647647 0.39528506]
  [0.92280215 0.14682925 0.2608037  0.51187656]]

 [[0.08278671 0.07633405 0.68101361 0.55538277]
  [0.50776733 0.39933212 0.7740028  0.51269081]
  [0.51692746 0.32082688 0.64763975 0.7856357 ]]]
zeroes are: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
ones are: [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
fulls are: [[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [15]:
type(data)

numpy.ndarray

In [ ]:
#---READING NUMPY---
shape = data.shape
print(f'shape is: {shape}')
size = data.size
print(f'size is: {size}')
types = data.dtype
print(f'data type is: {types}')

shape is: (2, 3, 4)
size is: 24
data type is: float64


In [20]:
#slicing
print(f'data is: {data}')
arr = data[0]
print(f'arr is: {arr}')
slicer = data[0][0:2]
print(f'slicer is: {slicer}')
reverse = data[-1]
print(f'reverse is: {reverse}')
singleval = data[0][0][0]
print(f'singleval is: {singleval}')

data is: [[[0.77301624 0.59130293 0.67632542 0.56653796]
  [0.27426246 0.34685099 0.4370695  0.20005405]
  [0.50330122 0.11874723 0.326178   0.68709326]]

 [[0.65291502 0.84191465 0.08794216 0.43381135]
  [0.86441242 0.15726122 0.77553291 0.72265528]
  [0.25978855 0.34548807 0.58022946 0.00121967]]]
arr is: [[0.77301624 0.59130293 0.67632542 0.56653796]
 [0.27426246 0.34685099 0.4370695  0.20005405]
 [0.50330122 0.11874723 0.326178   0.68709326]]
slicer is: [[0.77301624 0.59130293 0.67632542 0.56653796]
 [0.27426246 0.34685099 0.4370695  0.20005405]]
reverse is: [[0.65291502 0.84191465 0.08794216 0.43381135]
 [0.86441242 0.15726122 0.77553291 0.72265528]
 [0.25978855 0.34548807 0.58022946 0.00121967]]
singleval is: 0.7730162373602774


In [21]:
#----Update------

list1=np.random.rand(10)
print(f'list1: {list1}')
list2=np.random.rand(10)
print(f'list2: {list2}')    

add = np.add(list1,list2)
print(f'addition: {add}')
sub = np.subtract(list1,list2)
print(f'subtraction: {sub}')
mul = np.multiply(list1,list2)
print(f'multiplication: {mul}')
div = np.divide(list1,list2)
print(f'division: {div}')
dot = np.dot(list1,list2)      #dot product
print(f'dot product: {dot}')


list1: [0.30813725 0.86973832 0.25284018 0.71192857 0.3575253  0.94096893
 0.50449952 0.58031757 0.24939868 0.19625804]
list2: [0.86756287 0.98211847 0.43301238 0.12797851 0.83821302 0.60170017
 0.54076964 0.15888478 0.6925895  0.9055253 ]
addition: [1.17570011 1.85185679 0.68585255 0.83990708 1.19573831 1.5426691
 1.04526917 0.73920235 0.94198819 1.10178334]
subtraction: [-0.55942562 -0.11238015 -0.1801722   0.58395007 -0.48068772  0.33926876
 -0.03627012  0.42143279 -0.44319082 -0.70926726]
multiplication: [0.26732843 0.85418607 0.10948293 0.09111156 0.29968236 0.56618117
 0.27281803 0.09220363 0.17273091 0.17771662]
division: [0.3551757  0.88557373 0.58390982 5.56287612 0.42653275 1.56385019
 0.9329287  3.6524428  0.36009596 0.21673391]
dot product: 2.903441696305376


In [22]:
#-----Statistics----- saplemm
sqrt = np.sqrt(list1)
print(f'square root: {sqrt}')
mean = np.mean(list1)
print(f'mean: {mean}')
absval = np.abs(list1)
print(f'absolute value: {absval}')
pow = np.power(list1,2)
print(f'power: {pow}')
log = np.log(list1)
print(f'logarithm: {log}')
exp = np.exp(list1)
print(f'exponential: {exp}')
maxval = np.max(list1)
print(f'maximum value: {maxval}')
minval = np.min(list1)
print(f'minimum value: {minval}')


square root: [0.55510111 0.93259762 0.50283216 0.8437586  0.59793419 0.97003553
 0.7102813  0.76178578 0.49939832 0.44301021]
mean: 0.49716123655930905
absolute value: [0.30813725 0.86973832 0.25284018 0.71192857 0.3575253  0.94096893
 0.50449952 0.58031757 0.24939868 0.19625804]
power: [0.09494856 0.75644475 0.06392815 0.50684229 0.12782434 0.88542252
 0.25451977 0.33676849 0.0621997  0.03851722]
logarithm: [-1.17720999 -0.13956289 -1.3749977  -0.33977769 -1.02854915 -0.06084516
 -0.68418839 -0.54417978 -1.38870252 -1.62832494]
exponential: [1.36088775 2.38628633 1.28767746 2.03791775 1.42978674 2.56246306
 1.65615644 1.78660572 1.28325354 1.21684086]
maximum value: 0.9409689272354076
minimum value: 0.19625804208967434


In [38]:
#----Updating-----
data[0][0][0] = 10
print(f'updated data: {data}')
data.sort()
print(f'sorted data: {data}')
data= data.reshape((2,2,-1))
data.shape


data=np.append(data, 5)

zeroes = np.zeros(8)
zeroes = np.append(zeroes, [1,2,3])
print(f'zeroes after append: {zeroes}')

zeroes = np.insert(zeroes, 0, [4,5,6])
print(f'zeroes after insert: {zeroes}')


updated data: [[[10.          0.43834858  0.48581088  0.15098541]
  [ 0.60829044  0.4784295   0.79647647  0.39528506]
  [ 0.92280215  0.14682925  0.2608037   0.51187656]]

 [[ 0.08278671  0.07633405  0.68101361  0.55538277]
  [ 0.50776733  0.39933212  0.7740028   0.51269081]
  [ 0.51692746  0.32082688  0.64763975  0.7856357 ]]]
sorted data: [[[ 0.15098541  0.43834858  0.48581088 10.        ]
  [ 0.39528506  0.4784295   0.60829044  0.79647647]
  [ 0.14682925  0.2608037   0.51187656  0.92280215]]

 [[ 0.07633405  0.08278671  0.55538277  0.68101361]
  [ 0.39933212  0.50776733  0.51269081  0.7740028 ]
  [ 0.32082688  0.51692746  0.64763975  0.7856357 ]]]
zeroes after append: [0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3.]
zeroes after insert: [4. 5. 6. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3.]


In [49]:
#------delete-----
data = np.random.rand(2,3,4)
print(f'data before delete: {data}')
data = np.delete(data, 0)
print(f'data after delete: {data}')
np.save('new array', data)

test = np.load('new array.npy')
print(f'loaded array: {test}')

data before delete: [[[0.9457481  0.33684971 0.18433668 0.71514422]
  [0.17280405 0.1318939  0.36069584 0.87997421]
  [0.60308738 0.22645704 0.54971366 0.83687909]]

 [[0.32045573 0.29321396 0.14009039 0.44317202]
  [0.435886   0.3107541  0.19333913 0.24701498]
  [0.52169974 0.67281891 0.95368489 0.63520197]]]
data after delete: [0.33684971 0.18433668 0.71514422 0.17280405 0.1318939  0.36069584
 0.87997421 0.60308738 0.22645704 0.54971366 0.83687909 0.32045573
 0.29321396 0.14009039 0.44317202 0.435886   0.3107541  0.19333913
 0.24701498 0.52169974 0.67281891 0.95368489 0.63520197]
loaded array: [0.33684971 0.18433668 0.71514422 0.17280405 0.1318939  0.36069584
 0.87997421 0.60308738 0.22645704 0.54971366 0.83687909 0.32045573
 0.29321396 0.14009039 0.44317202 0.435886   0.3107541  0.19333913
 0.24701498 0.52169974 0.67281891 0.95368489 0.63520197]


In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("../data/raw/titanic3.csv")
df["money_wasted_cause_death"] = np.where(df["survived"]==0, df["fare"], 0) #np.where(condition, value_if_true, value_if_false)
df[["survived", "fare", "money_wasted_cause_death"]].head(10)
df["ticket/average money wasted"] = df["fare"]/(df["money_wasted_cause_death"].mean())
df[["fare", "money_wasted_cause_death", "ticket/average money wasted"]].head(10)

missing_count_fare = df["fare"].isnull().sum()
missing_count_age = df["age"].isnull().sum()
print(f'Missing values in fare column: {missing_count_fare}')
print(f'Missing values in age column: {missing_count_age}')

df["age"].fillna(df["age"].median(),inplace=True)
df["fare"].fillna(df["fare"].median(),inplace=True)
missing_count_fare = df["fare"].isnull().sum()                               # putting median value in missing areas
missing_count_age = df["age"].isnull().sum()                               # putting median value in missing areas
print(f'Missing values in fare column after imputation: {missing_count_fare}')
print(f'Missing values in age column after imputation: {missing_count_age}')     


df["fare_over_mean"] = df["fare"] / df["fare"].mean()
df["age_minus_median"] = df["age"] - df["age"].median()
df["fare_z"] = (df["fare"] - df["fare"].mean()) / df["fare"].std()
df[["fare", "fare_over_mean", "age", "age_minus_median", "fare_z"]].head(10)


df["is_child"]=np.where(df["age"]<18,1,0)
df[["age","is_child"]].head(10)
child_survived =np.sum(df["is_child"]&df["survived"])
percent_child_survived = child_survived/(np.sum(df["is_child"]))*100
adult_survived = np.sum((df["is_child"]==0)&df["survived"])
percent_adult_survived = adult_survived/(np.sum(df["is_child"]==0))*100
print(f'Percentage of children survived: {percent_child_survived}%')
print(f'Percentage of adults survived: {percent_adult_survived}%')

survival_by_child = df.groupby("is_child")["survived"].mean()
print(survival_by_child)
df.to_csv("../data/processed/titanic3_eda.csv", index=False)



Missing values in fare column: 1
Missing values in age column: 263
Missing values in fare column after imputation: 0
Missing values in age column after imputation: 0
Percentage of children survived: 52.5974025974026%
Percentage of adults survived: 36.277056277056275%
is_child
0    0.362771
1    0.525974
Name: survived, dtype: float64
